exclude: "^semgrep/tests/excluded_dir|semgrep/tests/lint|semgrep/tests/python|semgrep-core/tests|semgrep-core/old|semgrep-core/lib|semgrep-core/demos|semgrep-core/bin|.*\\.ml|.*\\.md"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.761"
    hooks:
      - id: mypy
        args: [--config, mypy.ini]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.9"
    hooks:
      - id: flake8
        args: ["--select=E9,F63,F7,F82"]
