exclude: "^semgrep/tests/e2e/(targets|snapshots)|semgrep-core/tests|.*\\.md"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^semgrep/tests/.+$
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.761"
    hooks:
      - id: mypy
        exclude: ^semgrep/tests/.+$
        args: [--config, mypy.ini]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.9"
    hooks:
      - id: flake8
        args: ["--select=E9,F63,F7,F82"]

  - repo: https://github.com/returntocorp/semgrep
    rev: 'v0.12.0'
    hooks:
      - id: semgrep
        args: ['--config', 'https://semgrep.live/p/python', '--include', '*.py', '--precommit', '--error']

  - repo: https://github.com/returntocorp/semgrep
    rev: 'v0.12.0'
    hooks:
      - id: semgrep
        args: ['--config', '.bento/semgrep.yml', '--include', '*.py', '--precommit', '--error']

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: docker_image
        entry: koalaman/shellcheck:v0.7.1
        files: ".sh"

  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        language: docker_image
        files: "Dockerfile"
        entry: hadolint/hadolint:v1.18.0 hadolint
        args: ["--ignore", "DL3008", "--ignore", "DL3018"]
