- id: semgrep-develop
  name: semgrep
  description: This hook runs semgrep:develop
  language: docker_image
  entry: returntocorp/semgrep:develop

- id: semgrep
  name: semgrep
  description: This hook runs semgrep
  language: docker_image
  entry: returntocorp/semgrep:latest
