exclude: "^tests|testlint|old|lib|demos|bin|.*\\.ml"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/returntocorp/sgrep
    rev: "0.4.3"
    hooks:
      - id: sgrep-develop
        args:
          [
            "--error",
            "--config",
            "r2c",
            "--output",
            "https://sgrep.r2c.dev/api/report/returntocorp/sgrep",
          ]
        types: [python]
