exclude: "^semgrep/tests/e2e/(targets|snapshots)|semgrep-core/tests|.*\\.md"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^semgrep/tests/.+$
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.761"
    hooks:
      - id: mypy
        exclude: ^semgrep/tests/.+$
        args: [--config, mypy.ini]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.9"
    hooks:
      - id: flake8
        args: ["--select=E9,F63,F7,F82"]

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: docker_image
        entry: koalaman/shellcheck:v0.7.1
        files: ".sh"
        args: ["--exclude=SC1004,SC1008,SC1009,SC1047,SC1050,SC1062,SC1071,SC1072,SC1090,SC1091,SC1105,SC1107,SC1123,SC1124,SC1126,SC2001,SC2002,SC2003,SC2004,SC2005,SC2006,SC2007,SC2009,SC2034,SC2035,SC2039,SC2155,SC2164,SC2181,SC2186,SC2196,SC2197,SC2230"]

  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        language: docker_image
        files: "Dockerfile"
        entry: hadolint/hadolint:v1.18.0 hadolint
        args: ["--ignore", "DL3008", "--ignore", "DL3010", "--ignore", "DL3012", "--ignore", "DL3018", "--ignore", "DL3020", "--ignore", "DL3022", "--ignore", "DL3027", "--ignore", "DL4001"]
