version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:2.4
    steps:
      - checkout
      - run: cd ~ && git clone  https://github.com/returntocorp/pfff
      - run: eval $(opam env) && cd ~/pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env); dune build
      - persist_to_workspace:
          root: /home/opam/project
          paths:
            - _build
  test:
    docker:
      - image: returntocorp/sgrep-build:2.4
    steps:
      - checkout
      - attach_workspace:
          at: /home/opam/project
      - run: cd ~ && git clone  https://github.com/returntocorp/pfff # TODO remove and just mount these two lines
      - run: eval $(opam env) && cd ~/pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env); dune runtest
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
