version: 2.1

executors:
  sgrep-build:
    docker:
      - image: returntocorp/sgrep-build:2.7

jobs:
  build:
    executor: sgrep-build
    steps:
      - checkout
      - run: git submodule init && git submodule update --remote
      - run: eval $(opam env) && cd ./pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env) && cd sgrep && make all
  build-lint:
    executor: sgrep-build
    steps:
      - checkout
      - run: cd sgrep_lint && make all
  test:
    executor: sgrep-build
    steps:
      - checkout
      - run: git submodule init && git submodule update --remote
      - attach_workspace:
          at: /home/opam/project
      - run: pip3 install -r sgrep_lint/requirements.txt
      - run: ln -s /home/opam/project/_build/default/bin/main_sgrep.exe /home/opam/.local/bin/sgrep
      - run: eval $(opam env) && cd ./pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env) && cd sgrep && make test && make && make install
      - run: cd sgrep_lint && make test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - build-lint
      - test:
          requires:
            - build
