version: 2.1
jobs:

  semgrep:
    docker:
      - image: returntocorp/semgrep:develop
        user: root
    working_directory: /src
    steps:
      - checkout
      - run: semgrep --config semgrep.yml --config https://semgrep.dev/p/ocaml --error --strict --verbose --exclude tests --exclude TODO --exclude _build .

  # For the benchmarks below, we had two alternatives:
  # A. run semgrep container from existing container: requires mounting
  #    a volume, which is disabled by CircleCI (results in empty folder
  #    once mounted).
  # B. run everything inside the semgrep container, which is very minimal
  #    since it doesn't even have bash. At least it has a suitable
  #    version of python.
  #
  # We use B out of necessity.
  #
  # Go through the same steps as the real benchmarks but quickly.
  dummy-benchmarks:
    docker:
      - image: returntocorp/semgrep:develop
    steps:
      - checkout
      - run:
          name: dummy benchmarks
          command: |
            cd perf
            ./run-benchmarks --dummy --upload

  # Real benchmarks
  benchmarks:
    docker:
      - image: returntocorp/semgrep:develop
    steps:
      - checkout
      - run:
          name: benchmarks
          command: |
            cd perf
            ./run-benchmarks --upload

workflows:
  version: 2
  semgrep:
    jobs:
      - semgrep

  # Daily semgrep benchmarks
  benchmarks:
    triggers:
      - schedule:
          # Run at 00:00 every day, UTC.
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - benchmarks:
          # Run only on these branches
          filters:
            branches:
              only:
                - develop

  # This is for testing. Requires pushing to a branch named 'dummy-benchmarks'.
  dummy-benchmarks-on-commit:
    jobs:
      - dummy-benchmarks:
          filters:
            branches:
              only:
                - dummy-benchmarks

  # This is for testing. Requires pushing to a branch named 'force-benchmarks'.
  # It can take hours, use with care.
  benchmarks-on-commit:
    jobs:
      - benchmarks:
          filters:
            branches:
              only:
                - force-benchmarks
