on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - "develop"
      - "master"
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Incorporate Benchmark Data
jobs:
  benchmark-persist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
        # TODO: once the job is working, build semgrep-core from source
      - name: Install semgrep-core from develop
        run: sudo -E ./install-scripts/latest-artifact-for-branch.py
        env:
          SEMGREP_CORE: "y"
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve the latest performance run
        run: ./install-scripts/latest-artifact-for-branch.py
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BENCHMARK: "y"
          # TODO: don't hardcode
          BRANCH: "develop"
          OUT_DIR: "semgrep/benchmarks"
      - name: Previous benches
        run: find semgrep/benchmarks
      - name: Check status
        run: ls -l
      - name: Install Tox and any other packages
        run: pip install pipenv==2018.11.26 wheel==0.34.2
      - name: Install semgrep
        run: |
          cd semgrep
          pipenv install --dev
      - name: check semgrep
        run: |
          cd semgrep
          pipenv run semgrep --version
      - name: run benchmarks
        run: |
          cd semgrep
          pipenv run pytest -k test_ci_perf tests/ --benchmark-only --benchmark-autosave --benchmark-storage benchmarks --benchmark-compare
      - name: Upload benchmark results
        uses: actions/upload-artifact@v1
        with:
          name: benchmarks
          path: semgrep/benchmarks
