name: Build Tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches:
      - develop

jobs:
  mac-build:
    name: Check builds for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      # - name: Setup Python
      #   uses: actions/setup-python@v1
      - name: Check Tooling
        run: which otool
      - name: Check lib
        run: ls /usr/local/opt/pcre/lib/
      # - name: Run OSX build
      #   run: ./scripts/osx-release.sh
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: semgrep-osx
          # path: artifacts

  # mac-build-linking-test:
  #   name: Check that semgrep-core runs
  #   runs-on: macos-latest
  #   needs: [mac-build]
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: semgrep-osx
  #         path: artifacts
  #     - name: Test build artifacts
  #       run: |
  #         chmod +x ./artifacts/semgrep-core
  #         chmod +x ./artifacts/spacegrep
  #         ./artifacts/semgrep-core -help
  #         ./artifacts/spacegrep --help
