name: ci

on:
  pull_request:
    push:
      branches: [master, develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build:2.7
    steps:
      - name: Adjust permissions
        run: sudo chmod -R 777 . /github
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Install pfff
        run: eval $(opam  env --root /home/opam/.opam --set-root) && opam install -y ./pfff
      - name: Install and test semgrep-core
        run: eval $(opam  env --root /home/opam/.opam --set-root) && cd semgrep-core && opam install -y . && make all && make test && make install
      - name: Install and test semgrep
        run: eval $(opam  env --root /home/opam/.opam --set-root) && cd semgrep && export PATH=/github/home/.local/bin:$PATH && make all && make test
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/bin/sgrep-lint-files
          cp ./semgrep-core/_build/default/bin/main_sgrep.exe artifacts/semgrep-core
          cp -r ./semgrep/build/semgrep.dist/* artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: sgrep-${{ github.sha }}
          path: artifacts
