name: build-wheels

on:
  push:
    branches: [master, develop, '**-test-release']

jobs:
  build-wheels-osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build the wheels
        run: ./release-scripts/build-wheels.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: osx-wheel
          path: semgrep/dist.zip
  build-wheels-ubuntu:
    strategy:
      matrix:
        os: ['ubuntu-16.04', 'ubuntu-18.04']
    runs-on: "${{ matrix.os }}"
    container: 'returntocorp/sgrep-build:${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Make Python happy
        run: |
          rm /usr/bin/python
          ln `which python3.7` /usr/bin/python
      - name: Install zip
        run: apt-get update && apt install -y zip
      - name: Build the wheels
        run: ./release-scripts/build-wheels.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: osx-wheel
          path: semgrep/dist.zip
