name: build-wheels

on:
  push:
    branches: [master, develop, '**-test-release']

jobs:
  build-wheels-osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build the wheels
        run: ./release-scripts/build-wheels.sh
  build-wheels-ubuntu:
    strategy:
      matrix:
        os: ['ubuntu-16.04', 'ubuntu-18.04']
    runs-on: "${{ matrix.os }}"
    container: 'returntocorp/sgrep-build:${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build the wheels
        run: ./release-scripts/build-wheels.sh
