name: Changelog Reminder
on: pull_request
jobs:
  changelog-reminder:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: semgrep_diff
        name: Get semgrep package diff
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: semgrep/semgrep
      - id: changelog_diff
        name: Get changelog diff
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: CHANGELOG.md

      - name: Send reminder
        uses: unsplash/comment-on-pr@v1.2.0
        if: >
          steps.semgrep_diff.outputs.insertions > 20
          && steps.changelog_diff.outputs.insertions == 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: You added quite a few lines in semgrep, but didn't update the changelog. Consider doing so!
          check_for_duplicate_msg: yes
