name: docker

on:
  pull_request:
    branches: [develop, master]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build .
      - name: build-and-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: returntocorp/semgrep
          tags: ${{ github.event.pull_request.head.sha }}
      - name: update sgrep.live
        run: curl --fail -X POST https://semgrep.live/api/admin/update-docker
