name: docker-push-pr

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build .
      - name: Push Develop Image if on develop branch
        if: ${{ github.event_name == 'push'}}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: returntocorp/semgrep
          tags: develop
      - name: Push Commit Hash if PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: returntocorp/semgrep
          tags: ${{ github.event.pull_request.head.sha }}
      - name: update semgrep.live
        run: curl --fail -X POST https://semgrep.live/api/admin/update-docker
