name: docker-push-dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Push Semgrep Docker Container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: returntocorp/semgrep
        tags: develop
    - name: update sgrep.live
      run: curl --fail -X POST https://semgrep.live/api/admin/update-docker
