name: Docker Builds

on:
  push:
    branches:
    - master
    - develop 
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: returntocorp/sgrep
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
