name: docker

on:
  push:
    branches:
    - master
    - develop
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: returntocorp/semgrep
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: update sgrep.live
      run: curl --fail -X POST https://sgrep.live/api/admin/update-docker
