name: Verify Homebrew Core Formula Works

on:
  pull_request:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 12 * * *'

jobs:
  mac-build:
    name: Check builds for macOS
    runs-on: macos-latest
    steps:
      - name: Brew update
        run: brew update
      - name: Brew Install
        run: brew install semgrep --HEAD
      - name: Check semgrep-core version
        run: semgrep-core --version
      - name: Check installed correctly
        run: brew test semgrep --HEAD
