name: mac-build

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]

jobs:
  mac-build-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          git remote set-url origin https://github.com/darlinghq/darling.git
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Brewfile
        run: brew bundle
      - name: opam Setup
        run: |
          opam init --no-setup --bare
          opam switch create 4.07.1
          opam switch 4.07.1
      - name: Build
        run: |
          eval "$(opam env)" && opam install -y ./pfff
          pushd semgrep-core && eval "$(opam env)" && opam install -y . && make all && make test && make install && popd
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp ./semgrep-core/_build/default/bin/main_semgrep_core.exe artifacts/semgrep-core
          zip -r artifacts.zip artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: semgrep-osx-${{ github.sha }}
          path: artifacts
