name: mac

on:
  push:
    # branches: [master, develop]

jobs:
  mac-build-test:
    runs-on: macos-latest
    steps:
      - name: Install System Deps
        run: brew install opam pkg-config coreutils
      - name: Checkout
        uses: actions/checkout@v2
      - name: OPAM setup
        run: |
          opam init --no-setup --bare;
          opam switch create 4.07.1;
          opam switch 4.07.1;
      - name: OPAM install Deps
        run: eval $(opam env); opam install -y reason dune ocamlfind camlp4 num ocamlgraph json-wheel conf-perl yaml
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Install pfff
        run: eval $(opam env) && cd ./pfff && ./configure && make depend && make && make opt && make install-libs
      - name: Install and test sgrep
        run: eval $(opam env) && cd sgrep && make all && make test && make install
      - name: Install and test sgrep-lint
        run: eval $(opam env) && cd sgrep_lint && export PATH=/github/home/.local/bin:$PATH && make all && make test
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/bin/sgrep-lint-files
          cp ./sgrep/_build/default/bin/main_sgrep.exe artifacts/sgrep
          cp -r ./sgrep_lint/build/sgrep.dist/* artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: sgrep-osx-${{ github.sha }}
          path: artifacts
