name: Create Draft Release

on:
  push:
    branches:
      # Sequence of patterns matched against refs/tags
      - '**-test-release'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  homebrew-core-pr:
    name: Update on Homebrew-Core
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_PR_TOKEN }}
          formula: semgrep

  brew-build:
    name: Check brew install formula works for develop head
    runs-on: macos-latest
    steps:
      - name: Brew update
        run: brew update
      - name: Brew Install
        run: brew install semgrep --HEAD
      - name: Check semgrep-core version
        run: semgrep-core -version
      - name: Check installed correctly
        run: brew test semgrep --HEAD
