name: release

on:
  push:
    # branches: [master, develop]

jobs:
  release-deb:
    runs-on: ubuntu-latest
    container: ocaml/opam2:debian-8
    steps:
      - name: Install System Deps
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends make m4 perl wget swi-prolog mercurial pkg-config python3 python3-pip python3-dev build-essential python3-setuptools
      - name: Update OPAM
        run: cd /home/opam/opam-repository && git pull && opam update
      - name: Adjust permissions
        run: sudo chmod -R 777 . /github
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache OPAM
        uses: actions/cache@v1
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-${{ hashFiles('.github/workflows/release.yml') }}
      - name: OPAM setup
        run: opam switch 4.07.1;
      - name: OPAM install Deps
        run: eval $(opam env); opam install -y reason dune ocamlfind camlp4 num ocamlgraph json-wheel conf-perl yaml
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Install pfff
        run: eval $(opam env) && cd ./pfff && ./configure && make depend && make && make opt && make install-libs
      - name: Install and test sgrep
        run: eval $(opam env) && cd sgrep && make all && make test && make install
      - name: Install and test sgrep-lint
        run: eval $(opam env) && cd sgrep_lint && export PATH=/github/home/.local/bin:$PATH && make all && make test
      - name: Clean Cache
        run: rm -rf ~/.opam/log
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/bin/sgrep-lint-files
          cp ./sgrep/_build/default/bin/main_sgrep.exe artifacts/sgrep
          cp -r ./sgrep_lint/build/sgrep.dist/* artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: sgrep-deb-jessie-${{ github.sha }}
          path: artifacts
