name: release-ubuntu-18-04

on:
  push:
    branches: [master, develop]

jobs:
  release-ubuntu-18-04:
    runs-on: ubuntu-latest
    container: ocaml/opam2:ubuntu-18.04
    steps:
      - name: Install System Deps
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends make m4 perl wget swi-prolog mercurial pkg-config python3.7 python3.7-dev python3.7-distutils build-essential
      - name: Install Python 3.7
        run: |
          sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          sudo -H python3.7 get-pip.py
          python3 --version
          pip3 --version
          ldd --version
          echo "Pls help me make this at least 3.7"
      - name: Install Git 2.18
        run: |
          sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev libexpat1-dev gettext libz-dev libssl-dev build-essential autoconf
          cd /usr/src/;
          sudo wget https://github.com/git/git/archive/v2.18.0.tar.gz -O git.tar.gz;
          sudo tar -xf git.tar.gz;
          cd git-*;
          sudo make prefix=/usr/local all;
          sudo make prefix=/usr/local install;
          git --version;
      - name: Adjust permissions
        run: sudo chmod -R 777 . /github
      - name: OPAM setup
        run: opam switch --root /home/opam/.opam 4.07;
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Install pfff
        run: eval $(opam env --root /home/opam/.opam --set-root) && opam install -y ./pfff
      - name: Build sgrep
        run: eval $(opam env --root /home/opam/.opam --set-root) && cd sgrep && opam install -y . && make all
      - name: Build sgrep-lint
        run: eval $(opam env --root /home/opam/.opam --set-root) && cd sgrep_lint && export PATH=/github/home/.local/bin:$PATH && make all
      - name: Prepare artifacts
        run: |
          mkdir -p sgrep-lint-files
          cp ./sgrep/_build/default/bin/main_sgrep.exe sgrep-lint-files/sgrep
          cp -r ./sgrep_lint/build/sgrep.dist/* sgrep-lint-files
          chmod +x sgrep-lint-files/sgrep
          chmod +x sgrep-lint-files/sgrep-lint
          chmod +x sgrep-lint-files/sgrep-lint-exe
          tar -cvzf sgrep-ubuntu-18.04.tar.gz sgrep-lint-files/

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: sgrep-ubuntu-18.04-${{ github.sha }}
          path: sgrep-ubuntu-18.04.tar.gz
