name: release

on:
  push:
    # branches: [master, develop]

jobs:
  release-deb:
    runs-on: ubuntu-latest
    container: ocaml/opam2:debian-8
    steps:
      - name: Install System Deps
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends make m4 perl wget swi-prolog mercurial pkg-config python3 python3-pip python3-dev build-essential python3-setuptools
      - name: Install Git 2.18
        run: |
          sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev libexpat1-dev gettext libz-dev libssl-dev build-essential autoconf
          cd /usr/src/;
          sudo wget https://github.com/git/git/archive/v2.18.0.tar.gz -O git.tar.gz;
          sudo tar -xf git.tar.gz;
          cd git-*;
          sudo make prefix=/usr/local all;
          sudo make prefix=/usr/local install;
          git --version;
      - name: Adjust permissions
        run: sudo chmod -R 777 . /github
      - name: OPAM setup
        run: opam switch --root /home/opam/.opam 4.07;
      - name: OPAM install Deps
        run: eval $(opam env --root /home/opam/.opam --set-root); opam install -y reason dune ocamlfind camlp4 num ocamlgraph json-wheel conf-perl yaml
      - name: Checkout
        uses: actions/checkout@v2
      - name: debugging
        run: ls -al .
      - name: Install pfff
        run: eval $(opam env --root /home/opam/.opam --set-root) && cd ./pfff && ./configure && make depend && make && make opt && make install-libs
      - name: Build sgrep
        run: eval $(opam env --root /home/opam/.opam --set-root) && cd sgrep && make all
      - name: Build sgrep-lint
        run: eval $(opam env --root /home/opam/.opam --set-root) && cd sgrep_lint && export PATH=/github/home/.local/bin:$PATH && make all
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/bin/sgrep-lint-files
          cp ./sgrep/_build/default/bin/main_sgrep.exe artifacts/sgrep
          cp -r ./sgrep_lint/build/sgrep.dist/* artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: sgrep-deb-jessie-${{ github.sha }}
          path: artifacts
