name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build
    steps:
      - uses: actions/checkout@v2
      - name: Install Python Deps
        run: pip3 install -r requirements.txt
      - name: Clone latest pfff
        run: git clone https://github.com/returntocorp/pfff /tmp/pfff
      - name: Install pfff
        run: eval $(opam env) && cd ~/pfff && ./configure && make depend && make && make opt && make install-libs
      - name: Build sgrep
        run: eval $(opam env); make all