name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: returntocorp/sgrep-build:2.5
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - name: Install Python Deps
        run: pip3 install -r requirements.txt
      - name: Clone latest pfff
        run: git clone https://github.com/returntocorp/pfff /tmp/pfff
      - name: Install pfff
        run: eval $(opam env) && cd ~/pfff && ./configure && make depend && make && make opt && make install-libs
      - name: Build sgrep
        run: eval $(opam env); make all
      - name: Add sgrep to Path
        run: ln -s /home/opam/project/_build/default/bin/main_sgrep.exe /home/opam/.local/bin/sgrep
      - name: Run tests
        run: eval $(opam env); make test