name: Tests

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches: [master, develop]

jobs:
  build-core:
    name: semgrep-core make test and semgrep make test/qa-test
    runs-on: ubuntu-latest
    container: ocaml/opam2:alpine
    steps:
      - name: Adjust permissions
        run: |
          sudo chmod -R 777 . /github
          # github cache dir
          sudo mkdir -p /__w/
          sudo chmod -R 777 /__w/
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build semgrep-core
        run: ./install-scripts/install-alpine-semgrep-core
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: semgrep-core
          path: artifacts/semgrep-core
      - name: Test semgrep-core
        run: |
          eval $(opam env --root /home/opam/.opam --set-root)
          cd semgrep-core
          make test

  build-test:
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: semgrep-core
          path: semgrep-core-dir
      - name: Install artifact
        run: |
          sudo cp semgrep-core-dir/semgrep-core /usr/bin/semgrep-core
          sudo chmod +x /usr/bin/semgrep-core
      - name: End-to-end tests
        run: |
          cd semgrep-core
          make e2etest
      - name: Install semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          pip3 install pipenv
          pipenv install --dev
      - uses: actions/cache@v2
        with:
          path: ~/.cache/semgrep-cache
          key: semgrep-repo-cache-test
      - name: create cache dir if not exists
        run: mkdir -p ~/.cache/semgrep-cache
      - run: touch ~/.cache/semgrep-cache/ok
      - name: Test semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          make ci-test
        env:
          GITHUB_REPO_CACHE: ~/.cache/semgrep-cache

  mac-build-test:
    name: Check builds for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          # This is just the Python version used to build the Nuitka executable
          python-version: 3.7
      - name: Run OSX build
        run: ./release-scripts/osx-release.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: semgrep-osx-${{ github.sha }}
          path: artifacts

  release-ubuntu:
    name: Check builds for ubuntu
    needs: [build-core]
    strategy:
      matrix:
        # The os doesn't actually matter anymore. We build a static
        # binary linked with musl that is manylinux compatible.
        os: ['ubuntu-16.04']
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build:${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: semgrep-core
          path: semgrep-core-dir
      - name: Install artifact
        run: |
          mkdir -p semgrep-files
          cp semgrep-core-dir/semgrep-core semgrep-files
          chmod +x semgrep-files/semgrep-core
      - name: Run Ubuntu build script
        run: ./release-scripts/ubuntu-release.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: semgrep-${{ matrix.os }}-${{ github.sha }}
          path: artifacts.tar.gz
