name: Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build-core:
    name: Build and Test semgrep-core
    runs-on: ubuntu-latest
    container: mjambon/r2c-ocaml:alpine
    steps:
      - name: Pre-checkout fixes
        run: |
          sudo chmod -R 777 /github
          github_cache_dir="/__w"
          sudo mkdir -p "$github_cache_dir"
          sudo chmod -R 777 "$github_cache_dir"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Post-checkout fixes
        run: ./.github/post-checkout
      - name: Build semgrep-core
        run: ./install-scripts/install-alpine-semgrep-core
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: semgrep-core
          path: artifacts/semgrep-core
      - name: Test semgrep-core
        run: |
          eval $(opam env)
          cd semgrep-core
          make test
          make e2etest

  tox-tests:
    name: semgrep tests with different python envs
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: semgrep-core
          path: semgrep-core-dir
      - name: Install artifact
        run: |
          sudo cp semgrep-core-dir/semgrep-core /usr/bin/semgrep-core
          sudo chmod +x /usr/bin/semgrep-core
      - name: Test semgrep-core
        run: semgrep-core -version
      - name: Install Tox and any other packages
        run: pip install pipenv==2018.11.26 wheel==0.34.2 tox==3.15.0
      - name: Run Tox
        run: |
          cd semgrep
          tox -e py  # Run tox using the version of Python in `PATH`


  build-test:
    name: semgrep unit and e2e tests
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: semgrep-core
          path: semgrep-core-dir
      - name: Install artifact
        run: |
          sudo cp semgrep-core-dir/semgrep-core /usr/bin/semgrep-core
          sudo chmod +x /usr/bin/semgrep-core
      - name: Install semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          pip3 install pipenv
          pipenv install --dev
      - uses: actions/cache@v2
        with:
          path: ~/.cache/semgrep-cache
          key: semgrep-repo-cache-test
      - name: create cache dir if not exists
        run: mkdir -p ~/.cache/semgrep-cache
      - run: touch ~/.cache/semgrep-cache/ok
      - name: Test semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          make ci-test
        env:
          GITHUB_REPO_CACHE: ~/.cache/semgrep-cache
