name: Semgrep Python Tests

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install semgrep-core from develop
        run: ./install-scripts/latest-artifact-for-branch.py
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: |
          cd semgrep
          tox -e py  # Run tox using the version of Python in `PATH`
